apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cookiecutter.service_name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{cookiecutter.service_name}}
  template:
    metadata:
      labels:
        app: {{cookiecutter.service_name}}
    spec:
      containers:
        - name: api
          image: {{cookiecutter.repo_name}}:latest
          ports:
            - containerPort: {{cookiecutter.service_port}}
          envFrom:
            - configMapRef:
                name: platform-config
            - secretRef:
                name: platform-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: {{cookiecutter.service_port}}
          livenessProbe:
            httpGet:
              path: /health
              port: {{cookiecutter.service_port}}
